'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const X=require('../src/expansion.js'),C=require('../src/core.js'),M=require('../src/scenery040.js'),G=require('../src/renderer3d.js');
const make=(mode='expedition',airframe='vanguard',seed='ASCENT')=>new X.Run(seed,'standard',false,{layout:'portrait',height:1000},{mode,airframe});
test('expedition content catalog has 6 bosses, 3 airframes, 8 relics and 3 new enemies',()=>{assert.equal(X.BOSSES.length,6);assert.equal(X.AIRFRAMES.length,3);assert.equal(X.RELICS.length,8);assert.equal(Object.keys(X.ENEMIES).length,3);for(const b of X.BOSSES)assert.ok(b.hp>0);});
test('all three airframes change actual initial hull, upgrades and dash cooldown',()=>{const v=make(),w=make('expedition','wraith'),b=make('expedition','bastion');assert.equal(v.upgrades.rail,1);assert.equal(w.upgrades.parry,1);assert.equal(b.upgrades.orbit,1);assert.equal(w.p.maxHp,v.p.maxHp-2);assert.equal(b.p.maxHp,v.p.maxHp+2);assert.ok(w.dashCooldown()<v.dashCooldown());assert.ok(b.dashCooldown()>v.dashCooldown());});
test('classic mode has no airframe mechanical advantages',()=>{const x=make('classic','bastion'),c=new C.World('ASCENT','standard',false,{layout:'portrait',height:1000});assert.equal(x.phase,'pact');assert.deepEqual(x.upgrades,c.upgrades);assert.equal(x.p.maxHp,c.p.maxHp);assert.equal(x.dashCooldown(),c.dashCooldown());});
test('route selection is single-use, invalid choices cannot mutate the run',()=>{const w=make();const before=w.report();assert.equal(w.chooseRoute('unknown'),false);assert.deepEqual(w.report(),before);assert.ok(w.chooseRoute('salvage'));assert.equal(w.credits,80);assert.equal(w.chooseRoute('salvage'),false);assert.equal(w.credits,80);});
test('recovery routes heal but never exceed maximum hull',()=>{const w=make();w.p.hp=3;w.chooseRoute('refuge');assert.equal(w.p.hp,5);});
test('director templates create different bounded plans, only between encounters',()=>{const plans=[];for(const id of Object.keys(X.DIRECTORS)){const w=make();assert.ok(w.setDirector(id));w.chooseRoute('elite');w.sign('mercy');plans.push(w.wavePlan.map(n=>n.type).join(','));assert.ok(w.wavePlan.length<=36);for(let i=1;i<w.wavePlan.length;i++)assert.ok(w.wavePlan[i].at-w.wavePlan[i-1].at>=1.049);assert.equal(w.setDirector('balanced'),false);}assert.equal(new Set(plans).size,3);});
test('all seed / sector / route combinations respect spawn positions and entity budget',()=>{for(let stage=0;stage<6;stage++)for(const route of X.ROUTES){const w=make();w.stage=stage;w.chooseRoute(route.id);w.sign(w.offersForPact()[0].id);for(const n of w.wavePlan){assert.ok(n.x>=w.bounds.left&&n.x<=w.bounds.right);assert.ok(n.y>=w.bounds.top&&n.y<=w.bounds.bottom);}assert.ok(w.wavePlan.length<=36);}});
test('shop rejects unaffordable, duplicate and non-offered relics; price is mechanical',()=>{const w=make(),r=w.shop[0];const before=w.credits;assert.equal(w.purchase(r.id),false);assert.equal(w.credits,before);w.credits=1000;assert.ok(w.purchase(r.id));assert.equal(w.credits,1000-r.cost);assert.equal(w.purchase(r.id),false);assert.equal(w.purchase('invented'),false);});
test('field repair only spends credits when there is damage and phase permits it',()=>{const w=make();assert.equal(w.repair(),false);w.p.hp-=3;assert.ok(w.repair());assert.equal(w.credits,15);w.p.hp-=2;assert.equal(w.repair(),false);});
test('relic needle and mercy lens alter projectiles; nova relic changes real cost',()=>{const w=make();w.relics=['needle','lens','nova'];const f=w.bullet(200,200,0,100,false),e=w.bullet(200,200,0,100,true);assert.equal(f.pierce,1);assert.ok(Math.abs(e.vx-100*.92*w.motionScale)<1e-6);assert.equal(w.novaCost(),85);});
test('second heart prevents one death and only once',()=>{const w=make();w.chooseRoute('salvage');w.sign('mercy');w.relics=['second'];w.p.inv=0;w.p.hp=1;assert.ok(w.hurt());assert.equal(w.phase,'combat');assert.equal(w.p.hp,3);w.p.inv=0;w.p.hp=1;w.hurt();assert.equal(w.phase,'dead');});
test('three new enemy controllers move or shoot and remain bounded',()=>{for(const type of Object.keys(X.ENEMIES)){const w=make();w.chooseRoute('salvage');w.sign('mercy');w.enemies=[];const e=w.spawn(type,300,200);e.spawn=0;e.fire=0;const count=w.bullets.length;w.updateEnemy(e,1/60);assert.ok(w.bullets.length>count);assert.ok(Number.isFinite(e.x+e.y));}});
test('new bosses have distinct actual attack signatures, independent of visuals',()=>{const signs=[];for(let stage=3;stage<6;stage++){const w=make();w.stage=stage;w.chooseRoute('salvage');w.wave=2;w.sign(w.offersForPact()[0].id);const b=w.enemies[0];b.spawn=0;b.fire=0;w.updateBoss(b,.016);signs.push(w.bullets.length+':'+b.fire);assert.ok(w.bullets.length>0);assert.equal(b.maxHp,w.bossInfo().hp*w.mods.hp*w.diffHp);}assert.equal(new Set(signs).size,3);});
function fixtureRun(mode){const w=make(mode);let steps=0;while(!['won','dead'].includes(w.phase)&&steps++<150){if(w.phase==='route')w.chooseRoute('refuge');else if(w.phase==='pact')w.sign(w.offersForPact()[0].id);else if(w.phase==='upgrade')w.chooseUpgrade(w.offers[0].id);else{w.wavePlan=[];w.planIndex=0;w.enemies=[];w.completeEncounter();}}return w;}
test('fixture progression: expedition completes 18 encounters and 6 signed pacts',()=>{const w=fixtureRun('expedition');assert.equal(w.phase,'won');assert.equal(w.encounters,18);assert.equal(w.contracts.length,6);assert.equal(w.routeHistory.length,6);});
test('fixture progression: gauntlet reaches six bosses and five upgrade drafts',()=>{const w=fixtureRun('gauntlet');assert.equal(w.phase,'won');assert.equal(w.encounters,6);assert.equal(w.contracts.length,6);assert.equal(w.log.filter(e=>e.type==='upgrade').length,5);});
test('same campaign inputs and seeds remain deterministic',()=>{const a=make(),b=make();for(const w of [a,b]){w.chooseRoute('elite');w.sign('mirror');}for(let i=0;i<1200;i++)for(const w of [a,b]){w.step(1/120,{shoot:true,autoAim:true,mx:Math.sin(i/100),my:Math.cos(i/80),parry:i%180===0});w.takeEvents();}assert.deepEqual(a.report(),b.report());assert.deepEqual(a.enemies,b.enemies);});
test('six scenic silhouettes, animation OFF stability and fixed geometry budgets',()=>{const signatures=[];for(let stage=0;stage<6;stage++){const w=make();w.stage=stage;const s=new M.Scene(),f={world:w,w:720,h:1000,t:0,bgAnim:0};s.build(f);const staticJSON=JSON.stringify(s.staticGroups);signatures.push(staticJSON);const budget=s.count;assert.ok(budget<3800);s.build({...f,t:12});assert.equal(JSON.stringify(s.staticGroups),staticJSON);assert.equal(s.count,budget);}assert.equal(new Set(signatures).size,6);});
test('crystal geometry finite; expanded scenes preserve foreground depth safety and world state',()=>{assert.ok(M.shapes.crystal.every(Number.isFinite));for(let stage=0;stage<6;stage++){const w=make();w.stage=stage;w.phase='combat';w.enemies=[];w.spawn('boss',360,220);w.enemies[0].spawn=0;const before=JSON.stringify(w),s=new M.Scene();const groups=s.build({world:w,w:720,h:1000,t:5});assert.equal(JSON.stringify(w),before);for(const a of Object.values(groups))for(let i=0;i<a.length;i+=16){const z=G.depth01(a[i+2],a[i+7]);assert.ok(z>=0&&z<=1);assert.ok(G.isFlight(a[i+7])?z<=G.DEPTH.flightFar:z>=G.DEPTH.sceneryNear);}}});

test('harrier pauses between strafing bursts so direct-aim shots can connect',()=>{const w=make();w.chooseRoute('refuge');w.sign('mercy');const e=w.spawn('harrier',360,200);e.spawn=0;e.age=2.5;const x=e.x,y=e.y;w.updateEnemy(e,.1);assert.equal(e.x,x);assert.equal(e.y,y);e.age=1;w.updateEnemy(e,.1);assert.notEqual(e.x,x);});

test('relic purchases cannot charge credits for an already capped upgrade',()=>{const w=new X.Run('CAPS','standard');w.credits=500;w.upgrades.echo=2;w.shop=[X.RELICS.find(r=>r.id==='echo')];assert.equal(w.purchase('echo'),false);assert.equal(w.credits,500);w.refreshShop();assert.ok(!w.shop.some(r=>r.id==='echo'));});
test('both mock and server provider options have valid opening tags',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert.match(html,/<option value="mock">/);assert.match(html,/<option value="server">/);assert.doesNotMatch(html,/<\/option\s+value=/);});
